# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=45)),
                ('artist_people', models.CharField(max_length=45)),
                ('artist_contact', models.CharField(max_length=45)),
                ('artist_vk', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
    ]
